name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      - name: Use use-axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const response = await axios.get('https://api.github.com');
            console.log(response.data);