name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      # options: --cpus 1

    steps:
      - name: Log Node & OS Version
        run: |
          echo "Node Version: $(node -v)"
          echo "OS Version: $(cat /etc/os-release)"
      - name: Log Environment Variables
        run: echo $API_URL