name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      # options: --cpus 1

    steps:
      - name: Log Node & OS Version
        run: |
          echo "Node Version: $(node -v)"
          echo "OS Version: $(cat /etc/os-release)"
      - name: Log Environment Variables
        run: echo $API_URL
      - name: Create a file
        run: echo "Hello World" > hello.txt
      - name: Container in step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Log Node Version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      - name: show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: hello.txt