name: Manually Triggered Workflow
on:
  workflow_dispatch:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow was triggered manually."
          echo "$GITHUB_REF"