name: Stale Issue and PRs
on:
  schedule:
    - cron: "0 14 * * *" # Every day at 14:00 UTC
    - cron: "0/5 * * * *" # Every 5 minutes
jobs: 
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been marked as stale due to inactivity. If no further activity occurs, it will be closed in 5 days.'
          days-before-stale: 1
          days-before-close: 5

