name: Sratus Check functions
on: [push]

  jobs:
    job-1:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: sleep 20
        - name: Runs on failure
          if: ${{ failure() }}
          run: echo "This step runs only if the previous step fails."
        - name: Runs on success
          if: ${{ success() }}
          run: echo "This step runs only if the previous step succeeds."
        - name: Runs on always
          if: ${{ always() }}
          run: echo "This step runs regardless of the previous step's outcome."
        - name: Runs on cancelled
          if: ${{ cancelled() }}
          run: echo "This step runs only if the workflow is cancelled."
    job-2:
      runs-on: ubuntu-latest
      needs: job-1
      if: ${{ failure() }}
      steps: 
        - run: echo "Job 2 runs only if Job 1 fails."
