name: Working Directory and Shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest 
    steps:
      - name: Display working directory & List Files
        run: |
          pwd 
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest 
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display working directory & List Files
        run: |
          Get-Locationn
          dir 
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python Shell
        run: |
          python --version
          import platform
          print(platform.processor())
  


