name: Worflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error wuth params 
        run: echo "::error title:Error title,file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"  
      - name: Setting an debug wuth params 
        run: echo "::debug title:Debug title,file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"    
      - name: Setting an warning wuth params 
        run: echo "::warning title:Warning title,file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting an notice wuth params 
        run: echo "::notice title:Notice title,file=app.js,line=2,endline=3,col=5,endColumn=7::Missing semicolon"
      - name: Group of logs
        run: |
          echo "::group::Group name"
          echo "This is a group of logs"
          echo "::endgroup::"
      - name: Masking a value
        run: echo "::add-mask::Secret String"
      - name: Echo a secret
        run: echo "Secret String"